### ISSUE TITLE
Mutations

### ISSUE THREAD

**Issue by petecoop** [mhart/simple-relay-starter#2]
Hey, thanks for creating this it's been a good help for starting out with Relay. It'd be really nice if you could add an example mutation, maybe to add a widget. It's something that looking at facebook's examples seems like a lot of boilerplate without much explanation

**Comment by mhart** [comment]
Yeah, unfortunately that's just the way mutations are at the moment – a lot of boilerplate – or at least a lot of code in any case. I deliberately didn't include them because of that reason – it would make the code a little harder to understand, so I left them out with the intent that users would be able to include them once they understand the basics.

If they become a little simpler (less verbose) to implement (and they're certainly looking at ways to make that happen), then I'll definitely revisit this. Thanks!

**Comment by petecoop** [comment]
mutations branch? :disappointed: Thanks anyways, hope they become simpler soon!
